# Generated by Django 4.2.16 on 2025-04-28 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentor_mentee', '0003_alter_participant_hackathon_role_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='areas_for_personal_growth',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='long_term_goals',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='preferred_learning_style',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='short_term_goals',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='strengths_and_weaknesses',
        ),
    ]
