# Generated by Django 4.2.16 on 2025-04-28 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mentor_mentee', '0004_remove_participant_areas_for_personal_growth_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MentorMenteeRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mentee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_relationship', to='mentor_mentee.participant')),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentees_relationship', to='mentor_mentee.participant')),
            ],
            options={
                'unique_together': {('mentor', 'mentee')},
            },
        ),
    ]
