# Generated by Django 4.2.16 on 2025-04-28 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mentor_mentee', '0005_mentormenteerelationship'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('session_id', models.AutoField(primary_key=True, serialize=False)),
                ('session_type', models.CharField(choices=[('virtual', 'Virtual'), ('physical', 'Physical')], max_length=10)),
                ('date_time', models.DateTimeField()),
                ('meeting_link', models.URLField(blank=True, null=True)),
                ('location', models.TextField(blank=True, null=True)),
                ('summary', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_sessions', to='mentor_mentee.participant')),
                ('participants', models.ManyToManyField(related_name='participating_sessions', to='mentor_mentee.participant')),
            ],
        ),
    ]
