# Generated by Django 4.2.16 on 2025-04-29 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mentor_mentee', '0006_session'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizResult',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quiz_topic', models.CharField(max_length=255)),
                ('score', models.IntegerField()),
                ('total_questions', models.IntegerField()),
                ('percentage', models.FloatField()),
                ('quiz_date', models.DateTimeField(auto_now_add=True)),
                ('quiz_data', models.JSONField(blank=True, null=True)),
                ('quiz_answers', models.JSONField(blank=True, null=True)),
                ('result_details', models.JSONField(blank=True, null=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_results', to='mentor_mentee.participant')),
            ],
            options={
                'ordering': ['-quiz_date'],
            },
        ),
    ]
