# Generated by Django 4.2.16 on 2025-04-30 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor_mentee', '0008_quizresult_completed_date_quizresult_mentor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentormenteerelationship',
            name='manually_created',
            field=models.BooleanField(default=True),
        ),
    ]
