# Generated by Django 4.2.16 on 2025-05-01 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor_mentee', '0009_mentormenteerelationship_manually_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='interest_preference1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='interest_preference2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='interest_preference3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
