# Generated by Django 4.2.16 on 2025-05-04 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mentor_mentee', '0010_participant_interest_preference1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('points_required', models.IntegerField()),
                ('image_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='participant',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='participant',
            name='badges_earned',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='participant',
            name='deactivation_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='is_super_mentor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='participant',
            name='leaderboard_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='participant',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('graduated', 'Graduated'), ('deactivated', 'Deactivated')], default='active', max_length=20),
        ),
        migrations.CreateModel(
            name='ParticipantBadge',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('earned_date', models.DateTimeField(auto_now_add=True)),
                ('is_claimed', models.BooleanField(default=False)),
                ('claimed_date', models.DateTimeField(blank=True, null=True)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mentor_mentee.badge')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earned_badges', to='mentor_mentee.participant')),
            ],
            options={
                'unique_together': {('participant', 'badge')},
            },
        ),
    ]
