# Generated by Django 4.2.16 on 2025-05-05 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_department_student_is_department_admin_and_more'),
        ('mentor_mentee', '0011_badge_participant_approval_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentoring_participants', to='account.department'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='branch',
            field=models.CharField(choices=[('cse', 'CSE'), ('ct', 'CT'), ('aids', 'AIDS'), ('aiml', 'AIML'), ('cse-iot', 'CSE-IOT'), ('etc', 'ETC'), ('ee', 'EE'), ('me', 'ME'), ('ce', 'CE'), ('it', 'IT'), ('csd', 'CSD')], max_length=10),
        ),
    ]
