# Generated by Django 4.2.16 on 2025-05-05 19:07

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_department_student_is_department_admin_and_more'),
        ('mentor_mentee', '0012_participant_department_alter_participant_branch'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationFeedback',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('usability_rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('features_rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('performance_rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('overall_rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('nps_score', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('what_you_like', models.TextField(blank=True, null=True)),
                ('what_to_improve', models.TextField(blank=True, null=True)),
                ('feature_requests', models.TextField(blank=True, null=True)),
                ('additional_comments', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('anonymous', models.BooleanField(default=False)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_feedback', to='mentor_mentee.participant')),
            ],
        ),
        migrations.CreateModel(
            name='MentorFeedback',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('communication_rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('knowledge_rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('availability_rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('helpfulness_rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('overall_rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('strengths', models.TextField(blank=True, null=True)),
                ('areas_for_improvement', models.TextField(blank=True, null=True)),
                ('additional_comments', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('anonymous', models.BooleanField(default=False)),
                ('mentee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_feedback', to='mentor_mentee.participant')),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_feedback', to='mentor_mentee.participant')),
                ('relationship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='mentor_mentee.mentormenteerelationship')),
            ],
            options={
                'unique_together': {('relationship',)},
            },
        ),
        migrations.CreateModel(
            name='FeedbackSettings',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mentor_feedback_enabled', models.BooleanField(default=False)),
                ('app_feedback_enabled', models.BooleanField(default=False)),
                ('feedback_start_date', models.DateTimeField(blank=True, null=True)),
                ('feedback_end_date', models.DateTimeField(blank=True, null=True)),
                ('allow_anonymous_feedback', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.department')),
            ],
            options={
                'unique_together': {('department',)},
            },
        ),
    ]
