# Generated by Django 4.2.16 on 2025-05-13 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_otp'),
        ('mentor_mentee', '0013_applicationfeedback_mentorfeedback_feedbacksettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='department',
            field=models.ForeignKey(blank=True, help_text="If set, this badge is specific to the department. If null, it's a global badge.", null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.department'),
        ),
    ]
