# Generated by Django 4.2.16 on 2025-05-13 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentor_mentee', '0014_badge_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='badge',
            name='department',
        ),
    ]
