# Generated by Django 4.2.16 on 2025-05-13 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor_mentee', '0015_remove_badge_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='participantbadge',
            name='linkedin_shared',
            field=models.BooleanField(default=False),
        ),
    ]
