# Generated by Django 4.2.16 on 2025-05-14 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor_mentee', '0016_participantbadge_linkedin_shared'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
