# Generated by Django 4.2.16 on 2025-05-15 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='google_refresh_token',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='google_scopes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='google_token',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='google_token_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='google_token_uri',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
